server:
  port: 8081

#database
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:tododb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

#webclient
client:
  timeout:
    connect: 10000
    read: 5000

#actuator
management:
  endpoints.web.base-path: /

#documentation
springdoc:
  version: '1.5.4'
  api-docs:
    path: /api-docs

#logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.david.todo: DEBUG
    reactor.netty.http.client: INFO
  pattern:
    console: '%highlight(<<%-5level>>) %d{HH:mm:ss:SSS} [%thread] %magenta(%c{0}.%M) - %m%n'