server:
  port: 8081

spring:
  #database
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tododb
    username: api_todo
    password: api@1234

#webclient
client:
  timeout:
    connect: 10000
    read: 5000

#actuator
management:
  endpoints.web.base-path: /

#documentation
springdoc:
  version: '1.5.4'
  api-docs:
    path: /api-docs

#logging
logging:
  level:
    root: INFO
    org.springframework:
      web: DEBUG
      data.r2dbc: DEBUG
    com.david.todo: DEBUG
    reactor.netty.http.client: INFO

  pattern:
    console: '%highlight(<<%-5level>>) %d{HH:mm:ss:SSS} [%thread] %magenta(%c{0}.%M) - %m%n'